# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-29 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210128_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '职位', 'verbose_name_plural': '职位列表'},
        ),
        migrations.AlterField(
            model_name='job',
            name='job_city',
            field=models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '深圳'), (3, '杭州'), (4, '广州')], verbose_name='工作地点'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.SmallIntegerField(choices=[(0, '技术类'), (1, '产品类'), (2, '运营类'), (3, '设计类'), (4, '市场营销类')], verbose_name='职位类型'),
        ),
    ]
